<a href="https://colab.research.google.com/github/manower35/LearningGitHub56/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy**

In [3]:
print("hellow numpy")

hellow numpy


In [4]:
import numpy as np

In [8]:
integers = np.array([1, 2, 6, 9 ,0])
integers

array([1, 2, 6, 9, 0])

In [9]:
integers[2]

6

In [12]:
integers[4] = 20
integers

array([20,  2,  6,  9, 20])

In [14]:
integers[1] = 30.5
integers

array([20, 30,  6,  9, 20])

In [15]:
integers.dtype

dtype('int64')

In [18]:
smaller_integers = np.array([100,110,111], dtype = np.int8)
smaller_integers

array([100, 110, 111], dtype=int8)

In [19]:
integers.nbytes

40

In [20]:
smaller_integers.nbytes

3

multidimensional array

In [25]:
nums = np.array([[1,2,5,3],[5,0,8,2]])
nums

array([[1, 2, 5, 3],
       [5, 0, 8, 2]])

In [27]:
nums[1,3]

2

In [35]:
three_dimen = np.array([[[2,4,7.8],[5,0,8]],[[2,4,9],[8,0,5]]])
three_dimen

array([[[2. , 4. , 7.8],
        [5. , 0. , 8. ]],

       [[2. , 4. , 9. ],
        [8. , 0. , 5. ]]])

In [37]:
three_dimen[1,1,0]

8.0